apiVersion: image.openshift.io/v1
kind: ImageStream
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  generation: 1
  labels:
    build: tatproxy
  name: tatproxy
  selfLink: /apis/image.openshift.io/v1/namespaces/tatproxy-ci-cd/imagestreams/tatproxy
spec:
  lookupPolicy:
    local: false
status:
  dockerImageRepository: image-registry.openshift-image-registry.svc:5000/tatproxy
