apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  annotations:
    openshift.io/generated-by: OpenShiftNewBuild
  creationTimestamp: null
  labels:
    build: tatproxy
  name: tatproxy
spec:
  failedBuildsHistoryLimit: 5
  nodeSelector: null
  output:
    to:
      kind: ImageStreamTag
      name: tatproxy:latest
  postCommit: {}
  resources: {}
  runPolicy: Serial
  source:
    dockerfile: |
      FROM openshift/nodejs:latest
      EXPOSE 8080
      COPY src/ index.js main.css package.json yarn.loc ${HOME}
      RUN npm install
      ENTRYPOINT ["npm", "start"]
    type: Dockerfile
  strategy:
    dockerStrategy:
      from:
        kind: ImageStreamTag
        name: nodejs:latest
        namespace: openshift
    type: Docker
  successfulBuildsHistoryLimit: 5
  triggers:
  - github:
      secret: zTfOgoi1WPTJu91DKbbr
    type: GitHub
  - generic:
      secret: TlPsztgJPueQkhFg-tjh
    type: Generic
  - type: ConfigChange
  - imageChange:
      lastTriggeredImageID: image-registry.openshift-image-registry.svc:5000/openshift/nodejs@sha256:74a3ef2964efc03dfc239da3f09691b720ce54ff4bb47588864adb222133f0fc
    type: ImageChange
status:
  lastVersion: 1
